<?php

/**
 * @file
 * Hook implementations for HipChat so we can respond to various system events.
 */

/**
 * Implements hook_menu().
 */
function hipchat_menu() {
  $items = array();
  $items['admin/config/services/hipchat'] = array(
    'title' => 'HipChat settings',
    'description' => 'Settings for the HipChat integration module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hipchat_admin_form'),
    'access arguments' => array('administer hipchat'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function hipchat_permission() {
  return array(
    'administer hipchat' => array(
      'title' => t('Administer HipChat'),
      'description' => t('Perform administration tasks for HipChat.'),
    ),
  );
}

/**
 * Form for the HipChat admin page.
 */
function hipchat_admin_form() {
  $form['hipchat_token'] = array(
    '#type' => 'textfield',
    '#title' => t('HipChat token'),
    '#description' => t('Get an Admin API token from !hipchat_link', array('!hipchat_link' => l(t('your HipChat admin page'), 'https://www.hipchat.com/group_admin/api'))),
    '#default_value' => variable_get('hipchat_token', NULL),
  );
  $form['hipchat_default_room'] = array(
    '#type' => 'textfield',
    '#title' => t('HipChat default room'),
    '#description' => t('Enter the default room to send notices. Enter the human name, not the room id'),
    '#default_value' => variable_get('hipchat_default_room', NULL),
  );

  return system_settings_form($form);
}

/**
 * A wrapper around the HipChat.php to send messages.
 *
 * @param string $message
 *   The message to send. Keep it relatively brief.
 * @param string $room
 *   Optional room to send it to (defaults to the sitewide value).
 * @param string $site_name
 *   Optional "site name" defaults to the Drupal site name.
 */
function hipchat_send($message, $room = NULL, $site_name = NULL) {
  require_once 'hipchat-php//src/HipChat/HipChat.php';

  // Ensure the site_name is less than 15 characters -- an API limit of HipChat.
  $room = empty($room) ? variable_get('hipchat_default_room', 'Development') : $room;
  $site_name = empty($site_name) ? variable_get('site_name', 'Drupal site') : $site_name;
  $site_name = substr($site_name, 0, 15);
  $token = variable_get("hipchat_token", NULL);
  $hc = new HipChat\HipChat($token);

  // Messages won't send properly without all three of these.
  if (empty($site_name) || empty($room) || empty($message)) {
    watchdog('hipchat', 'Skipping sending a message because site_name, room or message were empty');
    return;
  }

  $data = array('room' => $room, 'message' => $message);
  drupal_alter('hipchat_send_message', $data);

  try {
    $hc->message_room($room, $site_name, $message);
  }
  catch (HipChat\HipChat_Exception $e) {
    $params = array(
      '@room' => $room,
      '@msg' => $e->getMessage(),
    );
    watchdog('hipchat', 'Error sending message to room @room: @msg', $params, WATCHDOG_ERROR);
  }

}
